---
molecule:
  hosts:
    deb12-primary:
    deb12-replica:

deb12:
  hosts:
    deb12-primary:
    deb12-replica:

postgresql:
  hosts:
    deb12-primary:
    deb12-replica:

replica:
  hosts:
    deb12-replica:
      postgresql_primary_host: deb12-primary
