---
molecule:
  hosts:
    deb12-pg15-primary:
    deb12-pg15-replica:
    deb12-pg18-primary:
    deb12-pg18-replica:

deb12:
  hosts:
    deb12-pg15-primary:
    deb12-pg15-replica:
    deb12-pg18-primary:
    deb12-pg18-replica:

postgresql:
  hosts:
    deb12-pg15-primary:
    deb12-pg15-replica:
    deb12-pg18-primary:
    deb12-pg18-replica:

pg15:
  hosts:
    deb12-pg15-primary:
    deb12-pg15-replica:

pg18:
  hosts:
    deb12-pg18-primary:
    deb12-pg18-replica:

replica:
  hosts:
    deb12-pg15-replica:
      postgresql_primary_host: deb12-pg15-primary
    deb12-pg18-replica:
      postgresql_primary_host: deb12-pg18-primary
