---
molecule:
  hosts:
    deb12-pg15:
    deb12-pg18:

deb12:
  hosts:
    deb12-pg15:
    deb12-pg18:

postgresql:
  hosts:
    deb12-pg15:
    deb12-pg18:

pg15:
  hosts:
    deb12-pg15:

pg18:
  hosts:
    deb12-pg18:
