---
galaxy_info:
  author: Hachyderm
  description: >-
    An Ansible role for configuring [PGDG Apt
    repository](https://wiki.postgresql.org/wiki/Apt).
  license: Apache
  min_ansible_version: "2.12"
