---
- name: Destroy container instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['molecule'] }}"
      failed_when: false
