---
name: Ansible Documentation Release
concurrency:
  group: ansible-documentation-release-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: read
    name: build
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: hachyderm.general
      init-project: Hachyderm General Collection
      init-copyright: Hachyderm contributors
      init-title: Hachyderm General Collection Documentation
      init-html-short-title: Hachyderm General Collection Documentation
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_type }}/${{ github.ref_name }}
      squash-hierarchy: true
      init-lenient: false
      init-fail-on-error: true

  publish:
    # use to prevent running on forks
    if: github.repository == 'hachyderm/ansible'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs:
      - build
    name: publish
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
